import re
import sqlite3
from pathlib import Path

import pandas as pd
from databricks import sql

from config import (
    DATABRICKS_SERVER_HOSTNAME,
    DATABRICKS_HTTP_PATH,
    DATABRICKS_TOKEN,
    DEMO_MODE,
)

DEMO_DB = Path(__file__).parent / "demo_data.db"


def _prepare_demo_query(query: str) -> str:
    """Translate the small Databricks SQL subset used by the demo to SQLite."""
    q = query.strip().rstrip(";")

    # The LLM is instructed to use the production three-part names.
    q = re.sub(r"\bdc_operations\.gold\.", "", q, flags=re.IGNORECASE)

    # Databricks DATE_SUB(CURRENT_DATE(), 1) -> SQLite equivalent.
    q = re.sub(
        r"DATE_SUB\s*\(\s*CURRENT_DATE\s*\(\s*\)\s*,\s*(\d+)\s*\)",
        lambda m: f"DATE('now','-{m.group(1)} day')",
        q,
        flags=re.IGNORECASE,
    )

    # A few common Databricks date expressions.
    q = re.sub(
        r"CURRENT_DATE\s*\(\s*\)",
        "DATE('now')",
        q,
        flags=re.IGNORECASE,
    )

    # SQLite uses ROUND/AVG/SUM/COUNT and standard JOIN/WHERE/LIMIT syntax,
    # which covers the read-only demo queries generated by the app.
    return q


def execute_query(query: str):
    if DEMO_MODE:
        if not DEMO_DB.exists():
            raise FileNotFoundError(f"Demo database not found: {DEMO_DB}")

        with sqlite3.connect(DEMO_DB) as connection:
            return pd.read_sql_query(_prepare_demo_query(query), connection)

    if not all([DATABRICKS_SERVER_HOSTNAME, DATABRICKS_HTTP_PATH, DATABRICKS_TOKEN]):
        raise RuntimeError(
            "Databricks credentials are missing. Set DEMO_MODE=true for the public demo "
            "or configure DATABRICKS_SERVER_HOSTNAME, DATABRICKS_HTTP_PATH and DATABRICKS_TOKEN."
        )

    with sql.connect(
        server_hostname=DATABRICKS_SERVER_HOSTNAME,
        http_path=DATABRICKS_HTTP_PATH,
        access_token=DATABRICKS_TOKEN,
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
            rows = cursor.fetchall()
            columns = [col[0] for col in cursor.description]
            return pd.DataFrame(rows, columns=columns)
